config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: csv_dest
      host: 114.70.235.40
      pass: dke!!214!!
      port: 25432
      schema: public
      threads: 8
      type: postgres
      user: knu
  target: prod
